---
Description: ECS Cluster

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resources.
    Type: String

  ApplicationName:
    Description: Application Name
    Type: String

  ApplicationTaskDefinition:
    Description: Application Task Definition
    Type: String

  ContainerName:
    Description: Application Container Name
    Type: String

  ContainerPort:
    Description: Application Container Port
    Type: String

Resources:
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECS security group
      GroupName: ECSSG
      VpcId:
        Fn::ImportValue: !Sub ${ApplicationName}VpcId
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        Description: Port 5000
        FromPort: 5000
        ToPort: 5000
        IpProtocol: tcp
      Tags:
      - Key: Name
        Value: !Ref EnvironmentName

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${ApplicationName}EcsCluster

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !GetAtt ECSCluster.Arn
      ServiceName: !Sub ${ApplicationName}EcsService
      TaskDefinition: !Ref ApplicationTaskDefinition
      LoadBalancers:
      - ContainerName: !Ref ContainerName
        ContainerPort: !Ref ContainerPort
        TargetGroupArn:
          Fn::ImportValue:
            !Sub ${ApplicationName}BlueTargetGroupArn
      LaunchType: FARGATE
      SchedulingStrategy: REPLICA
      DeploymentController:
        Type: CODE_DEPLOY
      PlatformVersion: LATEST
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
          - !Ref ECSSecurityGroup
          Subnets:
            Fn::Split:
            - ","
            - Fn::ImportValue:
                !Sub ${ApplicationName}SubnetIds
      DesiredCount: 1

Output:
  EcsClusterName:
    Description: Application ECS Cluster.
    Value: !Ref ECSCluster
    Export:
      Name:
        !Join
        - ""
        - - !Ref ApplicationName
          - EcsClusterName

  EcsServiceName:
    Description: Application ECS Service.
    Value: !GetAtt ECSService.Name
    Export:
      Name:
        !Join
        - ""
        - - !Ref ApplicationName
          - EcsServiceName
