---
Description: Amazon CloudWatch Alarm on an Amazon S3 Bucket.

Parameters:
  S3BucketName:
    Type: String
    Description: S3 Bucket Name.

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName

  CloudWatchS3Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: S3 Bucket Alarm.
      AlarmName: S3BucketAlarm
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      Statistic: Minimum
      MetricName: BucketSizeBytes
      Namespace: AWS/S3
      Period: 60
      Threshold: 1000
      Dimensions:
      - Name: StorageType
        Value: StandardStorage
      - Name: BucketName
        Value: !Ref S3BucketName

  CloudTrailS3Trail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: S3NewYork
      EventSelectors:
      - DataResources:
        - Type: AWS::S3::Object
          Values:
          - !GetAtt S3Bucket.Arn
        IncludeManagementEvents: false
        ReadWriteType: All
      
