#!/bin/sh

aws cloudformation list-stacks \
  --query "StackSummaries[?(
      StackStatus == 'CREATE_COMPLETE' ||
      StackStatus == 'UPDATE_COMPLETE' ||
      StackStatus == 'CREATE_IN_PROGRESS' ||
      StackStatus == 'DELETE_IN_PROGRESS' ||
      StackStatus == 'UPDATE_IN_PROGRESS' ||
      StackStatus == 'UPDATE_ROLLBACK_IN_PROGRESS' ||
      StackStatus == 'UPDATE_ROLLBACK_COMPLETE' ||
      StackStatus == 'ROLLBACK_IN_PROGRESS' ||
      StackStatus == 'ROLLBACK_COMPLETE')]"
